#basic definitions
experiment_name: "urocell"
num_classes: 3
class_names: 
  - "back"
  - "lyso"
  - "mito"
  
#set the directories for data and models
data_dir: "/data/IASEM/conradrw/data/benchmarks/urocell/2d/"
model_dir: "/data/conradrw/models/"

#pixel norm values for the training dataset
norms:
    mean: 0.76752738
    std: 0.10404078
    
#pick the encoder for the resnet
#currently, only resnet50 is supported
encoder: "resnet50"

#weights for the CrossEntropy Loss
#by class (background, lysosome, mitochondria)
class_weights:
  - 0.1
  - 1
  - 1
  
#whether to log the run in MLFlow
#either True or False
logging: True

#number of times to print/record metrics for 
#train and validation data over the entire
#training run
num_prints: 10

#number of model checkpoints to save during training
#if zero, the model's state is never saved
num_save_checkpoints: 1

#if a .pth file is given for resume, weights will be 
#loaded into the model. If restart_training is False
#the optimizer and lr scheduler will also be resumed
#If True instead, weights will be loaded but a new
#training cycle will be started
resume: ""
restart_training: False

#number of workers to use for the Dataloader
jobs: 8

#choice of none, layer4, layer3, layer2, layer 1, or all
finetune_layer: "none"
#choice of True or False
unfreeze_encoder_bn: False

#set the encoder pretraining choice of:
#random_init, imagenet_supervised, imagenet_mocov2, cellemnet_mocov2 
#or a path to a custom .pth file with a state_dict
pretraining: "cellemnet_mocov2"

#hyperparameters for all lr policies
bsz: 16
lr: 0.003
wd: 0.1
#choice of AdamW or SGD
optim: "AdamW"
#choice of OneCycle, MultiStep, or Poly
lr_policy: "OneCycle"

#parameter only for SGD optim; AdamW uses default momentum values
momentum: 0.9

#iterations are used for Poly and OneCycle,
#epochs are used for MultiStep
iters: 5000

#parameters specific for Poly lr_policy
power: 0.9

#parameters specific to MultiStep lr_policy
epochs: 10
lr_decay_epochs:
  - 6
  - 8
  
#currently only IoU is supported
metrics:
  - "IoU"

#list the augmentations to use during training
augmentations:
  - aug: "PadIfNeeded"
    min_height: 224
    min_width: 224
  - aug: "RandomResizedCrop"
    height: 224
    width: 224
    scale:
      - 0.08
      - 1.0
    ratio:
      - 0.5
      - 1.5
  - aug: "Rotate"
    limit: 180
  - aug: "RandomBrightnessContrast"
    brightness_limit: 0.3
    contrast_limit: 0.3
  - aug: "HorizontalFlip"
  - aug: "VerticalFlip"
  
###INFERENCE SECTION 3D###
test_dir3d: "/data/conradrw/benchmarks/urocell/3d/test/"
mode3d: "orthoplane"
threshold3d: 0.5
eval_classes3d:
  - 1
  - 2
mask_prediction3d: False
save_dir3d: null